### PR TITLE
bugfix/NUI-5742-Screen-reader-reads-all-characteristics-of-Image-and-Icon

### PR DESCRIPTION
**Pull request by Vita-Karas**

### CODE REVIEW

**Review by DmytroPutrin — APPROVED** [review]

**Comment by Blakesalot** [comment]
Out of curiosity, @Vita-Karas what did you change to fix this? It's hard to tell by looking at the diffs.

**Comment by Blakesalot** [comment]
@Vita-Karas, do we need to make the same changes in the [nova-images](https://bitbucket.solarwinds.com/projects/NOVA/repos/nova-images/browse/src/images) repository? The open-source ones in this repository are only a subset of the larger collection in nova-images which are used by solarwinds products.

**Comment by ewok-janitor** [comment]
> @Vita-Karas, do we need to make the same changes in the [nova-images](https://bitbucket.solarwinds.com/projects/NOVA/repos/nova-images/browse/src/images) repository? The open-source ones in this repository are only a subset of the larger collection in nova-images which are used by solarwinds products.

you mean https://github.com/solarwindscloud/nova-assets?

**Comment by Vita-Karas** [comment]
@Blakesalot , you are right. We need to make the same changes in the nova-images repo. Created ticket for that https://jira.solarwinds.com/browse/NUI-6002

**Comment by Vita-Karas** [comment]
> Out of curiosity, @Vita-Karas what did you change to fix this? It's hard to tell by looking at the diffs.

I have add <style **aria-hidden='true'**>. Without this aria-label the screen reader reads the whole text inside the style tag.

**Review by dmytrofirsov — APPROVED** [review]

**Review by ivankozlovskyi — APPROVED** [review]

**Pull request merged**
